version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_NAME: 'users'
      DB_USER: 'chatapp'
      DB_PASSWORD: 'chatappsecured'

  postgre-server:
    image: postgres
    container_name: some-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'users'
      POSTGRES_USER: 'chatapp'
      POSTGRES_PASSWORD: 'chatappsecured'