version: '3.9'

services:
  app:
    container_name: springboot-app
    image: springboot-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: some-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'usersdb'
      POSTGRES_USER: 'chatapp'
      POSTGRES_PASSWORD: 'chatappsecured'